---
- name: Check Ubuntu version
  hosts: localhost
  tasks:
    - name: Gather Ubuntu facts
      ansible.builtin.setup:
        gather_subset:
          - all

    - name: Display Ubuntu version
      debug:
        msg: "Ubuntu version is {{ ansible_distribution_version }}"
