---
- name: Connect to VPN using nmcli
  hosts: localhost
  tasks:
    - name: Connect to VPN
      command: nmcli con up id ray-digital-vpn

    - name: Display message after connecting to VPN
      debug:
        msg: "VPN connected successfully!"
