---
- name: Connect to VPN and update packages
  hosts: localhost
  become: yes
  tasks:
    - name: Connect to VPN
      command: nmcli con up id ray-digital-vpn

    - name: Wait for VPN connection to be established
      wait_for:
        host: localhost
        port: 80
        timeout: 30
      become: no
      ignore_errors: yes

    - name: Update packages using apt-get
      apt:
        update_cache: yes

    - name: Display update message
      debug:
        msg: "Packages have been updated."
