---
- name: Connect to VPN and update packages
  hosts: siemServer
  become: yes
  tasks:
    - name: Connect to VPN
      command: nmcli con up id ray-digital-vpn

    - name: Display update message
      debug:
        msg: "Packages have been updated."
