---
- name: Connect to VPN and update packages
  hosts: localhost
  become: yes
  tasks:
    - name: Connect to VPN
      command: nmcli con up id ray-digital-vpn

    - name: Update package cache
      apt:
        update_cache: yes

    - name: Show message after updating packages
      debug:
        msg: "Packages updated successfully"
